services:
  frontend:
    image: node:18-alpine
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    env_file:
      - ./frontend/.env
    environment:
      - HOST=frontend
    ports:
      - 3000:3000
      - 24678:24678
    command: >
      sh -c "npm install &&
             npm run dev"

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./api
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: unless-stopped

  rev_proxy:
    image: nginx:1.24.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
