# Generated by Django 4.2.2 on 2023-06-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('LECTURES', 'Lectures'), ('TUTORIALS', 'Tutorials'), ('LABS', 'Labs'), ('SHARED', 'Shared'), ('EXAMS', 'Exams'), ('ADDITIONAL', 'Additional'), ('INFO', 'Info')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='file',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.coursedata'),
            preserve_default=False,
        ),
    ]
