# Generated by Django 4.2.2 on 2023-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_course_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='retrieve_count',
            field=models.IntegerField(default=0),
        ),
    ]
