# Generated by Django 4.2.2 on 2023-07-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_retrieve_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_date',
            new_name='created_time',
        ),
    ]
